notes/urls.py
from django.contrib import admin
from django.urls import path,include
from notesapp import views
from django.contrib.auth import views as auth_view
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('login/',auth_view.LoginView.as_view(template_name='login.html'),name='login'),
    path('logout/',auth_view.LogoutView.as_view(),name='logout'),
    path('signup/',views.SignUp.as_view(),name='signup'),
    path('app/',include('notesapp.urls'))
]

notesapp/urls.py
from django.urls import path
from notesapp import views
app_name='app'
urlpatterns = [
path('create/',views.CreateNote.as_view(),name='create'),
path('notes/',views.ListNotes.as_view(),name='notes'),
path('notes/edit/<pk>',views.EditNotes.as_view(),name='edit'),
path('notes/<pk>',views.DetailNotes.as_view(),name='detail'),
path('notes/delete/<pk>',views.NotesDelete.as_view(),name='delete')
]

notesapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Note(models.Model):
    writer=models.ForeignKey(User,null=True,on_delete=models.CASCADE);
    title=models.CharField(max_length=200,null=True);
    text=models.CharField(max_length=1000);
    time_created=models.DateTimeField(null=True);
# Create your models here.

notesapp/forms.py
from django import forms
from django.contrib.auth.models import User
from notesapp import models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
class UserCreateForm(UserCreationForm):
    class Meta:
        fields =('first_name','last_name','username','email','password1','password2')
        model = User

notesapp/views.py
from django.shortcuts import render
from django.urls import reverse_lazy,reverse
from notesapp import forms
from django import forms as f
from notesapp import models
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView,CreateView,DeleteView,ListView,DetailView,UpdateView
from django.utils import timezone

def index(request):
    return render(request,'index.html')
class SignUp(CreateView):
    form_class = forms.UserCreateForm
    template_name='signup.html'
    success_url=reverse_lazy('login')
class CreateNote(LoginRequiredMixin,CreateView):
    login_url='login'
    template_name='createnote.html'
    model=models.Note
    fields=('title','text')
    success_url=reverse_lazy('app:notes')
    def get_form(self, form_class=None):
        form = super(CreateNote, self).get_form(form_class)
        form.fields['text'].widget = f.Textarea(attrs={"placeholder" : "Enter your text here..","rows" : 8,"cols":50    },);
        form.fields['text'].label='';
        form.fields['title'].widget= f.TextInput(attrs={"placeholder" : "Enter Title Here.."})
        return form
    def form_valid(self,form):
        self.object=form.save(commit=False)
        self.object.writer_id=self.request.user.id;
        self.object.time_created=timezone.now();
        self.object.save()
        return super(CreateNote,self).form_valid(form)
class ListNotes(LoginRequiredMixin,ListView):
    login_url='login'
    model=models.Note
    def get_queryset(self,*args,**kwargs):
        return models.Note.objects.all().filter(writer=self.request.user).order_by('-time_created');
class EditNotes(LoginRequiredMixin,UpdateView):
    login_url='login'
    model=models.Note
    fields=('title','text')
    template_name='createnote.html'
class DetailNotes(LoginRequiredMixin,DetailView):
    login_url='login'
    model=models.Note
class NotesDelete(LoginRequiredMixin,DeleteView):
    model=models.Note;
    login_url='login'
    success_url=reverse_lazy('app:notes')

notesapp/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>

    <!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> -->
<link rel="stylesheet" href="{% static 'icon.css' %}" >
<link rel="stylesheet" href="{% static 'title.css' %}" >
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
    <meta charset="utf-8">
    <title>Notes</title>
  </head>
  <body>
<section id="header">

    <h1 id="title" >Notsera</h1>

    </section>
    <section id="nav-bar">
        <nav class="navbar navbar-expand-lg ">
            <div class="container-fluid">
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon">  </span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav navbar-collapse">
                  <li class="nav-item" >
                    <a class="nav-link"  href="{% url 'index' %}">Home</a>
                  </li>
                  {% if user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'app:notes'%}">Your notes</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{%url 'logout'%}">Logout</a>
                  </li>
                  {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'login'%}">Login</a>
                  </li>
                    {% endif %}
                </ul>
              </div>
            </div>
          </nav>
    </section>





    <div id="block">
          <div class="row">
<div class="col-lg-7">
      {% block b1 %}

      {% endblock %}
</div>
      <div class="col-lg-5 ">


      <img id="gif" src="{% static 'note.gif' %}" alt="" height="400px" />    </div>
    </div>
    </div>
  </body>
</html>

notesapp/templates/createnote.html
{% extends 'base.html' %}
{% block b1 %}
{% if not form.instance.pk %}
{% load static%}
<h1>Add Details For Your Note!!</h1>
{% else %}
Edit Note
{% endif %}
<form  method="post" class="login-form">
{%csrf_token%}
{{form.as_p}}
<input type="submit" class="btn" id="login-submit" value="Save">


</form>
{% endblock %}

notesapp/templates/index.html
{% extends 'base.html' %}
{% block b1 %}
{%load static%}
<img src="{% static 'note.gif' %}" alt="" height="400px"/>
{% endblock %}

notesapp/templates/login.html
{% extends 'base.html' %}
{% block b1 %}
  <h1>
    <em>Enter your credentials to get logged in!!</em>
  </h1>
  <form method="post" class="login-form">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class="btn" id="login-submit" value="Login">
    <b><h4>New to NOTSERA?? <a href="{% url 'signup'%}" class="signup blink_me"> SIGN UP NOW</a></h4></b>
  </form>
{% endblock %}

notesapp/templates/notesapp/note_confirm_delete.html
{% extends 'base.html' %}
{% block b1 %}
<form class="login-form" method="post">
{%csrf_token%}
{{form.as_p}}
<p><font size=32>Are You Sure You Want to Delete this Note??</font></p>
<input type="submit" class="btn btn-danger" value="Confirm">
<a href="{%url 'app:detail' pk=object.id %}" class='btn btn-success'>Cancel</a>
</form>
{% endblock %}

notesapp/templates/notesapp/note_detail.html
{% extends 'base.html' %}
{% block b1 %}
{%load static%}

<h1 class="text-center text-uppercase">Title : {{ object.title}} </h1>
<p id="i1" class="font-weight-bold">Time Created : {{object.time_created}}</p>

<p id="content">{{ object.text }}<br><br><br></p>
<a href="edit/{{object.id}}"><img src="{% static 'download.jpg' %}" height=80 class='border'/></a>
<a href="{% url 'app:delete' pk=object.id %}"><img src="{% static 'delete.jpeg' %}" height=80 class='border'/></a>

{% endblock %}

notesapp/templates/notesapp/note_list.html
{% extends 'base.html' %}
{% block b1 %}
{%load static%}
<h3>
<ol>
  {% for note in note_list %}
    <li><a href="{{note.id}}" class="badge text-uppercase">{{note.title}}</a></li>
    {% empty %}
    <h1>No Notes Added Yet!!</h1>
    {% endfor %}
</ol>
</h3>
<a href="{% url 'app:create' %}"><img src="{% static 'download.jpg' %}" height=70 class="border"/></a>
{% endblock %}

notesapp/templates/signup.html
{% extends 'base.html' %}
{% block b1 %}
  <h1>
    <em>Enter Following Details to get started!!</em>
  </h1>
  <form method="post" class='login-form'>
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" id='signup-submit' value="Sign Up">
  </form>
{% endblock %}